/**
 * dsh-think-tools — download 卡片样式（命名空间 dtt-dl，幂等注入）。
 * 视觉基线与 dts__download-card 一致：--dts-accent 品牌蓝、bg-layer 表面、
 * 12px 圆角、细描边；进度条两态：确定比例填充+游标辉光 / 不定长游标滑动，
 * 均带过渡动画（用户偏好：UI 改动默认带动效）。
 */

const CSS = [
'/* ===== download 活进度卡片（对话流原子行 + 抽屉共用）================== */',
'.dtt-dl__card {',
'  --dts-accent: var(--dsw-alias-state-business-primary, #4176e6);',
'  --dtt-dl-surface: var(--dsh-flow-veil, color-mix(in srgb, var(--dsw-alias-label-primary) 5%, transparent));',
'  display: flex;',
'  flex-direction: column;',
'  gap: 6px;',
'  min-width: 300px;',
'  max-width: 560px;',
'  margin: 4px 0;',
'  padding: 10px 12px;',
'  border: 1px solid color-mix(in srgb, var(--dts-accent) 24%, var(--dsw-alias-border-l2, rgba(127,127,127,.22)));',
'  border-radius: 12px;',
'  background: linear-gradient(180deg, color-mix(in srgb, var(--dts-accent) 8%, transparent), transparent 62%), var(--dtt-dl-surface);',
'  box-shadow: 0 1px 3px rgba(15,17,21,.05);',
'  animation: dtt-dl-rise .32s cubic-bezier(.2,.8,.25,1) both;',
'  transition: border-color .2s ease, box-shadow .2s ease;',
'}',
'.dtt-dl__card[data-state="running"] {',
'  border-color: color-mix(in srgb, var(--dts-accent) 38%, var(--dsw-alias-border-l2, rgba(127,127,127,.22)));',
'  box-shadow: 0 2px 10px color-mix(in srgb, var(--dts-accent) 14%, rgba(15,17,21,.06));',
'  animation: dtt-dl-rise .32s cubic-bezier(.2,.8,.25,1) both, dtt-dl-breathe 2.4s ease-in-out .4s infinite;',
'}',
'.dtt-dl__card[data-state="failed"], .dtt-dl__card[data-state="cancelled"] {',
'  --dts-accent: var(--dsw-alias-state-error-primary, #e5484d);',
'}',
'@keyframes dtt-dl-rise { from { opacity: 0; transform: translateY(3px); } to { opacity: 1; transform: none; } }',
'@keyframes dtt-dl-breathe { 0%, 100% { box-shadow: 0 2px 10px color-mix(in srgb, var(--dts-accent) 14%, rgba(15,17,21,.06)); } 50% { box-shadow: 0 2px 14px color-mix(in srgb, var(--dts-accent) 26%, rgba(15,17,21,.06)); } }',
'',
'.dtt-dl__head {',
'  display: flex;',
'  align-items: center;',
'  gap: 7px;',
'  min-width: 0;',
'  color: var(--dts-accent);',
'  font-size: 12px;',
'  font-weight: 600;',
'}',
'.dtt-dl__head > svg { flex: none; }',
'.dtt-dl__title {',
'  min-width: 0;',
'  overflow: hidden;',
'  font-variant-numeric: tabular-nums;',
'  text-overflow: ellipsis;',
'  white-space: nowrap;',
'}',
'.dtt-dl__elapsed { color: var(--dsw-alias-label-tertiary); font-weight: 400; font-variant-numeric: tabular-nums; }',
'.dtt-dl__stats {',
'  display: inline-flex;',
'  gap: 8px;',
'  flex: none;',
'  margin-left: auto;',
'  color: var(--dsw-alias-label-secondary);',
'  font-size: 11px;',
'  font-weight: 400;',
'  font-variant-numeric: tabular-nums;',
'}',
'.dtt-dl__speed { color: var(--dts-accent); }',
'',
'.dtt-dl__url {',
'  min-width: 0;',
'  overflow: hidden;',
'  color: var(--dsw-alias-label-tertiary);',
'  font-family: var(--ds-font-family-code, monospace);',
'  font-size: 11px;',
'  line-height: 17px;',
'  text-overflow: ellipsis;',
'  white-space: nowrap;',
'}',
'',
'/* 轨道：确定态=比例填充；不定态=游标滑动。 */',
'.dtt-dl__track {',
'  position: relative;',
'  height: 5px;',
'  overflow: hidden;',
'  border-radius: 999px;',
'  background: color-mix(in srgb, var(--dts-accent, #4176e6) 14%, var(--dsw-alias-interactive-bg-hover, rgba(127,127,127,.12)));',
'}',
'.dtt-dl__fill {',
'  position: absolute;',
'  top: 0;',
'  bottom: 0;',
'  left: 0;',
'  border-radius: 999px;',
'  background: linear-gradient(90deg, color-mix(in srgb, var(--dts-accent) 72%, transparent), var(--dts-accent));',
'  transition: width .45s cubic-bezier(.25,.7,.3,1);',
'}',
'.dtt-dl__fill::after {',
"  content: '';",
'  position: absolute;',
'  top: 0;',
'  bottom: 0;',
'  right: 0;',
'  width: 26px;',
'  background: linear-gradient(90deg, transparent, rgba(255,255,255,.55));',
'  animation: dtt-dl-gleam 1.5s ease-in-out infinite;',
'}',
'@keyframes dtt-dl-gleam { 0%, 100% { opacity: .35; } 50% { opacity: 1; } }',
'.dtt-dl__cursor {',
'  position: absolute;',
'  top: 0;',
'  bottom: 0;',
'  width: 42%;',
'  border-radius: 999px;',
'  background: linear-gradient(90deg, transparent, var(--dts-accent), transparent);',
'  animation: dtt-dl-slide 1.15s cubic-bezier(.4, 0, .6, 1) infinite;',
'}',
'@keyframes dtt-dl-slide { from { left: -42%; } to { left: 100%; } }',
'',
'.dtt-dl__foot {',
'  display: flex;',
'  align-items: center;',
'  gap: 8px;',
'  min-width: 0;',
'  font-size: 11px;',
'  line-height: 17px;',
'}',
'.dtt-dl__pct { flex: none; color: var(--dts-accent); font-weight: 700; font-variant-numeric: tabular-nums; }',
'.dtt-dl__eta { flex: none; color: var(--dsw-alias-label-tertiary); font-variant-numeric: tabular-nums; }',
'.dtt-dl__dest {',
'  min-width: 0;',
'  overflow: hidden;',
'  color: var(--dsw-alias-label-tertiary);',
'  font-family: var(--ds-font-family-code, monospace);',
'  text-overflow: ellipsis;',
'  white-space: nowrap;',
'}',
'.dtt-dl__error { color: var(--dsw-alias-state-error-primary, #e5484d); }',
'.dtt-dl__open {',
'  flex: none;',
'  margin-left: auto;',
'  border: 1px solid var(--dsw-alias-border-l2, rgba(127,127,127,.22));',
'  border-radius: 999px;',
'  padding: 0 9px;',
'  background: transparent;',
'  color: var(--dsw-alias-label-secondary);',
'  font-size: 11px;',
'  line-height: 18px;',
'  cursor: pointer;',
'  transition: all .16s ease;',
'}',
'.dtt-dl__open:hover {',
'  border-color: color-mix(in srgb, var(--dts-accent) 40%, transparent);',
'  color: var(--dts-accent);',
'  transform: translateY(-1px);',
'  box-shadow: 0 2px 8px rgba(15,17,21,.08);',
'}',
'',
'@media (prefers-reduced-motion: reduce) {',
'  .dtt-dl__card, .dtt-dl__fill, .dtt-dl__fill::after, .dtt-dl__cursor, .dtt-dl__open { animation: none !important; transition: none !important; }',
'}',
].join('\n')

export function injectDownloadStyles(): void {
  if (typeof document === 'undefined') return
  if (document.getElementById('dsh-think-tools-download-styles') !== null) return
  const style = document.createElement('style')
  style.id = 'dsh-think-tools-download-styles'
  style.textContent = CSS
  document.head.appendChild(style)
}