/** proto-tabs 交互卡片样式（命名空间 dtt-proto__，幂等注入）。 */

const CSS = [
'/* 容器：总结卡正文内的独立卡片，留白 breathing room */',
'.dtt-proto {',
'  --dtp-accent: var(--dsw-alias-state-business-primary, #4176e6);',
'  margin: 12px 0 4px;',
'  border: 1px solid var(--dsw-alias-border-l2, rgba(127,127,127,.22));',
'  border-radius: 16px;',
'  padding: 16px 16px 12px;',
'  background: var(--dsw-alias-bg-layer-1, rgba(127,127,127,.04));',
'  animation: dtt-proto-rise .45s cubic-bezier(.2,.8,.25,1) both;',
'}',
'@keyframes dtt-proto-rise {',
'  from { opacity: 0; transform: translateY(10px) }',
'  to { opacity: 1; transform: none }',
'}',
'.dtt-proto__head {',
'  display: flex; align-items: center; justify-content: space-between;',
'  gap: 10px; flex-wrap: wrap;',
'  padding-bottom: 12px; margin-bottom: 12px;',
'  border-bottom: 1px solid var(--dsw-alias-border-l2, rgba(127,127,127,.18));',
'}',
'.dtt-proto__title { display: flex; align-items: center; gap: 8px; font-size: 12px; opacity: .65 }',
'.dtt-proto__dot { width: 7px; height: 7px; border-radius: 50%; background: var(--dtp-accent); box-shadow: 0 0 0 4px color-mix(in srgb, var(--dtp-accent) 15%, transparent) }',
'.dtt-proto__tabs { display: flex; gap: 6px; background: var(--dsw-alias-bg-layer-2, rgba(127,127,127,.09)); padding: 3px; border-radius: 999px; flex-wrap: wrap }',
'.dtt-proto__tab { border: 0; background: transparent; font-size: 12px; padding: 6px 12px; border-radius: 999px; cursor: pointer; color: inherit; opacity: .65; font-family: inherit; transition: all .22s ease }',
'.dtt-proto__tab:hover { opacity: 1; color: var(--dtp-accent); transform: translateY(-1px) }',
'.dtt-proto__tab--active { background: var(--dsw-alias-bg-layer-1, #fff); opacity: 1; color: var(--dtp-accent); font-weight: 700; box-shadow: 0 2px 10px rgba(65,118,230,.20) }',
'.dtt-proto__panel { animation: dtt-proto-fade .32s cubic-bezier(.2,.8,.25,1) both }',
'@keyframes dtt-proto-fade {',
'  from { opacity: 0; transform: translateY(8px) }',
'  to { opacity: 1; transform: none }',
'}',
'.dtt-proto__heading { display: flex; align-items: center; gap: 8px; font-size: 12px; font-weight: 600; color: #4caf50; margin: 2px 0 10px }',
'.dtt-proto__heading::before { content: ""; width: 6px; height: 6px; border-radius: 50%; background: currentColor }',
'/* pill 行：hover 上浮 + 辉光 */',
'.dtt-proto__pill { display: flex; align-items: center; gap: 10px; border: 1.5px solid color-mix(in srgb, var(--dtp-accent) 25%, transparent); border-radius: 999px; padding: 10px 14px; cursor: pointer; transition: all .25s ease }',
'.dtt-proto__pill:hover { border-color: var(--dtp-accent); box-shadow: 0 6px 22px rgba(65,118,230,.18); transform: translateY(-1px) scale(1.004) }',
'.dtt-proto__bulb { width: 30px; height: 30px; flex: none; border-radius: 50%; background: radial-gradient(circle at 35% 30%, color-mix(in srgb, var(--dtp-accent) 55%, #fff), color-mix(in srgb, var(--dtp-accent) 12%, transparent)) }',
'.dtt-proto__tag { font-weight: 700; font-size: 12px; padding: 2px 9px; border-radius: 6px; white-space: nowrap; background: color-mix(in srgb, var(--dtp-accent) 13%, transparent); color: var(--dtp-accent) }',
'.dtt-proto__tag--dark { background: rgba(147,197,253,.16); color: #93c5fd }',
'.dtt-proto__desc { flex: 1; font-size: 12px; opacity: .65; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; min-width: 0 }',
'.dtt-proto__desc--dark { color: #94a3b8; opacity: 1 }',
'.dtt-proto__arrow { opacity: .4; transition: transform .25s ease }',
'.dtt-proto__arrow--open { transform: rotate(90deg) }',
'.dtt-proto__arrow--dark { color: #64748b; opacity: 1 }',
'.dtt-proto__detail { margin-top: 10px; font-size: 12.5px; padding: 12px 14px; border-radius: 10px; border: 1px dashed color-mix(in srgb, var(--dtp-accent) 40%, transparent); background: color-mix(in srgb, var(--dtp-accent) 6%, transparent); animation: dtt-proto-fade .3s ease both }',
'/* 可展开卡片 */',
'.dtt-proto__expand { border: 1.5px solid color-mix(in srgb, var(--dtp-accent) 25%, transparent); border-radius: 13px; overflow: hidden; transition: all .25s ease }',
'.dtt-proto__expand:hover { box-shadow: 0 8px 24px rgba(65,118,230,.15); transform: translateY(-2px) }',
'.dtt-proto__expand-head { display: flex; align-items: center; gap: 10px; padding: 12px 14px; cursor: pointer }',
'.dtt-proto__expand-body { padding: 2px 14px 14px; font-size: 12.5px; border-top: 1px dashed color-mix(in srgb, var(--dtp-accent) 30%, transparent); padding-top: 12px; margin: 0 14px 14px; padding-left: 0; padding-right: 0; animation: dtt-proto-fade .3s ease both }',
'/* 流光 */',
'.dtt-proto__glow { border-radius: 999px; padding: 2px; background: linear-gradient(110deg, #60a5fa, #a78bfa, #34d399, #60a5fa); background-size: 250% 100%; animation: dtt-proto-flow 4s linear infinite; cursor: pointer; transition: transform .25s ease }',
'.dtt-proto__glow:hover { transform: translateY(-2px) scale(1.008) }',
'@keyframes dtt-proto-flow { to { background-position: 250% 0 } }',
'.dtt-proto__glow-inner { background: #0f172a; color: #e2e8f0; border-radius: 999px; padding: 10px 14px; display: flex; align-items: center; gap: 10px }',
'.dtt-proto__spark { color: #fbbf24 }',
'/* 三小卡 */',
'.dtt-proto__minis { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin-top: 12px }',
'@media (max-width: 560px) { .dtt-proto__minis { grid-template-columns: 1fr } }',
'.dtt-proto__mini { border: 1px solid var(--dsw-alias-border-l2, rgba(127,127,127,.2)); border-radius: 10px; padding: 10px 12px; font-size: 12px; opacity: .9; transition: all .25s ease }',
'.dtt-proto__mini:hover { transform: translateY(-3px) scale(1.015); box-shadow: 0 10px 24px rgba(65,118,230,.15); border-color: color-mix(in srgb, var(--dtp-accent) 45%, transparent) }',
'.dtt-proto__mini b { display: block; color: var(--dtp-accent); font-size: 12.5px; margin-bottom: 2px }',
'.dtt-proto__hint { font-size: 11px; opacity: .45; margin-top: 10px; text-align: center }',
'/* 用户要求：去全部底色（流光描边与 hover 反馈保留）。 */',
'.dtt-proto, .dtt-proto__tabs, .dtt-proto__tab--active, .dtt-proto__tag, .dtt-proto__detail, .dtt-proto__expand, .dtt-proto__expand-body, .dtt-proto__mini, .dtt-proto__glow-inner { background: transparent !important; }',
'.dtt-proto { border: none !important; box-shadow: 0 2px 6px rgba(20,40,90,.10), 0 18px 44px rgba(20,40,90,.20) !important; }',
'body[data-ds-dark-theme] .dtt-proto { box-shadow: 0 4px 10px rgba(0,0,0,.45), 0 20px 52px rgba(0,0,0,.80) !important; }',
'@media (prefers-reduced-motion: reduce) {',
'  .dtt-proto, .dtt-proto__panel, .dtt-proto__detail, .dtt-proto__expand-body { animation: none }',
'  .dtt-proto__glow { animation: none }',
'  .dtt-proto__tab, .dtt-proto__pill, .dtt-proto__expand, .dtt-proto__glow, .dtt-proto__mini { transition: none }',
'}',
].join('\n')

export function injectProtoStyles(): void {
  if (typeof document === 'undefined') return
  if (document.getElementById('dsh-think-tools-proto-styles') !== null) return
  const style = document.createElement('style')
  style.id = 'dsh-think-tools-proto-styles'
  style.textContent = CSS
  document.head.appendChild(style)
}
